In [5]:
import numpy as np

arr_1=np.array([10,20,30,40,50,60])
print(arr_1)

#Numpy Array In-Built Methods and Properties

print(arr_1.shape) #shape return (rows,columns)
print(type(arr_1))
print(arr_1.dtype)  #dtype returns data type
print("Item size:",arr_1.itemsize)
print("Size",arr_1.size) #size()-Returns Total size of Array
print("Dimension",arr_1.ndim)  #dimensionality- 1D
print(arr_1.nbytes)  #nbytes=Total size of numpy array

[10 20 30 40 50 60]
(6,)
<class 'numpy.ndarray'>
int64
8
6
1
48


In [7]:
#Types of numpy array
#Create 1-D array
arr_2=np.array([10,20,23,43,30,48,57])

#create a 2-D array -matrix

arr_3=np.array([[18,11,13,15],
                [23,56,34,44],
                [0,45,4,34]])

print(arr_3.shape) #shape return (rows,columns)
print(type(arr_3))
print(arr_3.dtype)  #dtype returns data type
print("Item size:",arr_3.itemsize)
print("Size",arr_3.size) #size()-Returns Total size of Array
print("Dimension",arr_3.ndim)  #dimensionality- 1D
print(arr_3.nbytes)

(3, 4)
<class 'numpy.ndarray'>
int64
Item size: 8
Size 12
Dimension 2
96


In [10]:
#Three dimensional array

arr_4=np.array([[[18,11,13,15],
    [23,56,34,44],
    [0,45,4,34]],
    [[18,11,13,15],
    [1,1,1,1],
    [0,45,4,34]]])


print(arr_4)
print(arr_4.shape) #shape return (rows,columns)
print(type(arr_4))
print(arr_4.dtype)  #dtype returns data type
print("Item size:",arr_4.itemsize)
print("Size",arr_4.size) #size()-Returns Total size of Array
print("Dimension",arr_4.ndim)  #dimensionality- 1D
print(arr_4.nbytes)

[[[18 11 13 15]
  [23 56 34 44]
  [ 0 45  4 34]]

 [[18 11 13 15]
  [ 1  1  1  1]
  [ 0 45  4 34]]]
(2, 3, 4)
<class 'numpy.ndarray'>
int64
Item size: 8
Size 24
Dimension 3
192


In [21]:
#Slicing And Indexing In Numpy Array

print(arr_3[0]) #Indexing for first two elements
print(arr_3[:,:]) #All rows and all columns
print(arr_3[:,0]) #slicing elements from all rows and first column index
print(arr_3[:,0:2])  #slicing elements from all rows and first column index


print(arr_3[1:-1,1:-1]) #start index=1, stop index=last index position

#slicing 3 dimensional numpy array
print(arr_4[1,1,2]) #matrix 1 row 1 column 2




[18 11 13 15]
[[18 11 13 15]
 [23 56 34 44]
 [ 0 45  4 34]]
[18 23  0]
[[18 11]
 [23 56]
 [ 0 45]]
[[56 34]]
1
[1 1 1 1]


In [30]:
#create Numpy array using functions

arr_5=np.arange(1,51) #create 1-D array
print("Array 5:")
print(arr_5)

print("Array 6:")
array_6=np.arange(1,51).reshape(2,5,5)
print(array_6)

print("Array 7")
array_7=np.arange(1,51).reshape(5,10)
print(array_7)

Array 5:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Array 6:
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]
Array 7
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [48]:
#zero matrix : np.zero(shape)

arr_8=np.zeros((5,7),dtype='float16')
arr_9=np.zeros((5,7),dtype='int16')
print(arr_8)
print(arr_9)


#ones matrix 

arr_10=np.ones((5,7))
print(arr_10)

#identity matrix 

arr_10=np.identity(5)
print(arr_10)

#empty matrix 

arr_11=np.empty((3,3)) #not necessary it will get filled with zero
print(arr_11)

#fill all positions with 2
arr_11.fill(2)
print(arr_11)

#full

print(np.full(10,6.1))

#linspace
#creates an evenly spaced array

print(np.linspace(10,100,10)) #start position, stop position and number of elements


#logspace
#N evenly spaced array on a logscale between start and stop position

arr_12=np.logspace(0,1,10,base=2)
print(arr_12)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[6.1 6.1 6.1 6.1 6.1 6.1 6.1 6.1 6.1 6.1]
[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[1.         1.08005974 1.16652904 1.25992105 1.36079    1.46973449
 1.58740105 1.71448797 1.85174942 2.        ]


In [53]:
# Excersi-

#create a program that will generate output [1,1,1,1,1,1,1,1,1,1]
# a1=[]
# for i in range(0,10):
#     a=[]
#     for j in range(0,10):
#         if i==0 or j==0 or i==9 or j==9:
#             a.append(1)
#         else:
#             a.append(0)
#     a1.append(a)
# a1

np.arange()



[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

In [78]:
#create matrix where boundaries are 1's
a=np.ones((10,10))
a[1:-1,1:-1]=0
# a[0]=1
# a[9]=1
# a[:,0]=1
# a[:,9]=1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [87]:
#create a checkered box
b=np.zeros((10,10))
b[::2,::2]=1
b[1::2,1::2]=1
b

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [89]:
#Mathematical operations on Numpy Array

arr_13=np.array([[
            [1,3,5],
            [4,8,7],
            [9,11,13]],
         [[2,4,7],
          [3,1,5],
          [5,2,8]]])

In [96]:
print(arr_13.sum())
#row wise addition
print(arr_13.sum(axis=0))

#Column wise addition
print(arr_13.sum(axis=1))

#min()
print(arr_13.max())

#max()
print(arr_13.min())

#where() - returns index position for condition =True

arr_14=np.arange(1,21).reshape(5,4)
print(np.where(arr_14>8))



98
[[ 3  7 12]
 [ 7  9 12]
 [14 13 21]]
[[14 22 25]
 [10  7 20]]
13
1
(array([2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [108]:
arr_15=np.arange(1,37).reshape(6,6)
print(arr_15.mean()) #calculate mean
print(arr_15.mean(axis=0)) #calucalte mean row wise
print(arr_15.mean(axis=1)) #calculate mean column wise

print(np.std(arr_15)) #standard deviation
print(np.var(arr_15)) #variance

#Reversing an array

arr_16=np.arange(50)

#step size=-1
print(arr_16[0::-1])

#flip the array
print(np.flip(array_6))

#flip the rows up and down
print(np.flipud(array_6))

#flip the rows left and right
print(np.flipud(array_6))

#Flatten = To convert n- d Array into 1-D Array

array_17=np.random.randint(10,50, size=(5,3))
print(array_17)
print(arr_4.flatten())


18.5
[16. 17. 18. 19. 20. 21.]
[ 3.5  9.5 15.5 21.5 27.5 33.5]
10.388294694831615
107.91666666666667
[0]
[[[50 49 48 47 46]
  [45 44 43 42 41]
  [40 39 38 37 36]
  [35 34 33 32 31]
  [30 29 28 27 26]]

 [[25 24 23 22 21]
  [20 19 18 17 16]
  [15 14 13 12 11]
  [10  9  8  7  6]
  [ 5  4  3  2  1]]]
[[[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]]
[[[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]]
[[48 15 43]
 [41 39 14]
 [26 11 16]
 [49 17 19]
 [14 22 19]]
[18 11 13 15 23 56 34 44  0 45  4 34 18 11 13 15  1  1  1  1  0 45  4 34]


In [110]:
#ravel()- Flattens N-D array to 1-D Array

array_17=np.random.randint(10,50, size=(5,3))
print(array_17)
print(array_17.ravel())

[[32 31 41]
 [47 41 44]
 [25 18 43]
 [28 24 23]
 [29 24 27]]
[32 31 41 47 41 44 25 18 43 28 24 23 29 24 27]


In [116]:
# np.argmax() - Returns Index Position of maximum value along axis
array_17=np.random.randint(10,50, size=(5,3))
print(array_17)
print(np.argmax(array_17,axis=0))

print(np.argmax([0,0,0,0.8,0.5,0.5,1,0]))

[[49 28 19]
 [28 33 19]
 [28 45 21]
 [15 35 37]
 [28 26 19]]
[0 2 3]
6
